### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by jonas-schievink** [Guidobelix/archlinux-themes-sddm#2]
This theme looks great, but I'd be nice if HiDPI support was a little better. For example, the text box labels are so tiny that I almost can't read them:
![img_20160209_172300](https://cloud.githubusercontent.com/assets/1786438/12922545/3630c07a-cf52-11e5-8530-e47f30e8d2fc.jpg)

(sorry for the bad quality "screenshot" :P)

**Comment by Guidobelix** [comment]
I'll give it a try, but I don't have a HiDPI monitor myself, so I will have to count on you for testing :smile:

**Comment by jonas-schievink** [comment]
Awesome, thanks!

**Comment by Guidobelix** [comment]
@jonas-schievink, I need you to test a first release candidate, if you can.
I have created a branch called HiDPI.
Could you please download it and check how it displays on your monitor?
BTW, you don't need to install it, it is enough to run following command:
`sddm-greeter --theme /path/to/your/theme`
If you also could take a screenshot, that would be great, so I can fix what is still not OK

**Comment by jonas-schievink** [comment]
Looks great!
![2016-02-12-221333_2160x1440_scrot](https://cloud.githubusercontent.com/assets/1786438/13020486/f46153a4-d1d5-11e5-8725-ea69cf3f137d.png)

**Comment by Guidobelix** [comment]
Thanks for your test!
I'll use it for a day or two (just to make sure everything is working as it should) and then I'll release an update of the package.

**Comment by Guidobelix** [comment]
New version released on Aur
