### ISSUE TITLE
get a blanc sddm display when i try to remove layout box 

### ISSUE THREAD

**Issue by sniper1720** [Guidobelix/archlinux-themes-sddm#5]
hello 
i edit the main.qml file to remove layoutbox but i get blanc sddm (can't see nothing)
i do the following 
i delete the following lines 
`  Text {
                            id: lblLayout
                            width: parent.width / 3; height: archlinux.height / 9
                            text: textConstants.layout
                            verticalAlignment: Text.AlignVCenter
                            horizontalAlignment: Text.AlignHCenter
                            color: "white"
                            wrapMode: TextEdit.WordWrap
                            font.bold: true
                            font.pixelSize: archlinux.height / 22.5
                        }

```
                    LayoutBox {
                        id: layoutBox
                        width: (parent.width * 2 / 3) -10; height: archlinux.height / 9
                        font.pixelSize: archlinux.height / 20

                        arrowIcon: "angle-down.png"

                        KeyNavigation.backtab: session; KeyNavigation.tab: loginButton`
```

**Comment by sniper1720** [comment]
hello again 
hhhh i do a stupid step when editing the main.qml file the problem is just a one or two braces.

the problem is solved.

**Comment by Guidobelix** [comment]
:+1:
